// Generated by gencpp from file mujoco_ros_msgs/JointInit.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_JOINTINIT_H
#define MUJOCO_ROS_MSGS_MESSAGE_JOINTINIT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mujoco_ros_msgs
{
template <class ContainerAllocator>
struct JointInit_
{
  typedef JointInit_<ContainerAllocator> Type;

  JointInit_()
    : header()
    , name()  {
    }
  JointInit_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::mujoco_ros_msgs::JointInit_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mujoco_ros_msgs::JointInit_<ContainerAllocator> const> ConstPtr;

}; // struct JointInit_

typedef ::mujoco_ros_msgs::JointInit_<std::allocator<void> > JointInit;

typedef boost::shared_ptr< ::mujoco_ros_msgs::JointInit > JointInitPtr;
typedef boost::shared_ptr< ::mujoco_ros_msgs::JointInit const> JointInitConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mujoco_ros_msgs::JointInit_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mujoco_ros_msgs::JointInit_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mujoco_ros_msgs::JointInit_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::JointInit_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mujoco_ros_msgs::JointInit_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::JointInit_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mujoco_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::JointInit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::JointInit_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::JointInit_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::JointInit_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::JointInit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::JointInit_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mujoco_ros_msgs::JointInit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "526145fa7ec35edc4f233ec1bcfb4fdd";
  }

  static const char* value(const ::mujoco_ros_msgs::JointInit_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x526145fa7ec35edcULL;
  static const uint64_t static_value2 = 0x4f233ec1bcfb4fddULL;
};

template<class ContainerAllocator>
struct DataType< ::mujoco_ros_msgs::JointInit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/JointInit";
  }

  static const char* value(const ::mujoco_ros_msgs::JointInit_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mujoco_ros_msgs::JointInit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"string[] name\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mujoco_ros_msgs::JointInit_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mujoco_ros_msgs::JointInit_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointInit_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mujoco_ros_msgs::JointInit_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mujoco_ros_msgs::JointInit_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    if (v.name.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.name[i]);
    }
    if (v.name.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_JOINTINIT_H
