// Generated by gencpp from file mujoco_ros_msgs/SensorState.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_SENSORSTATE_H
#define MUJOCO_ROS_MSGS_MESSAGE_SENSORSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <mujoco_ros_msgs/SensorBase.h>

namespace mujoco_ros_msgs
{
template <class ContainerAllocator>
struct SensorState_
{
  typedef SensorState_<ContainerAllocator> Type;

  SensorState_()
    : header()
    , sensor()  {
    }
  SensorState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sensor(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::mujoco_ros_msgs::SensorBase_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::mujoco_ros_msgs::SensorBase_<ContainerAllocator> >> _sensor_type;
  _sensor_type sensor;





  typedef boost::shared_ptr< ::mujoco_ros_msgs::SensorState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mujoco_ros_msgs::SensorState_<ContainerAllocator> const> ConstPtr;

}; // struct SensorState_

typedef ::mujoco_ros_msgs::SensorState_<std::allocator<void> > SensorState;

typedef boost::shared_ptr< ::mujoco_ros_msgs::SensorState > SensorStatePtr;
typedef boost::shared_ptr< ::mujoco_ros_msgs::SensorState const> SensorStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mujoco_ros_msgs::SensorState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mujoco_ros_msgs::SensorState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mujoco_ros_msgs::SensorState_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::SensorState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.sensor == rhs.sensor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mujoco_ros_msgs::SensorState_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::SensorState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mujoco_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::SensorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::SensorState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::SensorState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::SensorState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::SensorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::SensorState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mujoco_ros_msgs::SensorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6a3e7ef3cb5a31ce0b40d3f6aa28a2f";
  }

  static const char* value(const ::mujoco_ros_msgs::SensorState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6a3e7ef3cb5a31cULL;
  static const uint64_t static_value2 = 0xe0b40d3f6aa28a2fULL;
};

template<class ContainerAllocator>
struct DataType< ::mujoco_ros_msgs::SensorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/SensorState";
  }

  static const char* value(const ::mujoco_ros_msgs::SensorState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mujoco_ros_msgs::SensorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"\n"
"SensorBase[] sensor\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: mujoco_ros_msgs/SensorBase\n"
"string name\n"
"\n"
"float64[] data\n"
;
  }

  static const char* value(const ::mujoco_ros_msgs::SensorState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mujoco_ros_msgs::SensorState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sensor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mujoco_ros_msgs::SensorState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mujoco_ros_msgs::SensorState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sensor: ";
    if (v.sensor.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.sensor.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::mujoco_ros_msgs::SensorBase_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.sensor[i]);
    }
    if (v.sensor.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_SENSORSTATE_H
